### ISSUE TITLE
disable on mobiles/tablets

### ISSUE THREAD

**Issue by outboxvision** [lwiesel/jquery-fadethis#3]
Hi, 
Great plugin!
I'm curios how can I disable the plugin on mobile/tablets because for some reason, if I use "slide-top" or "slide-bottom" it doesn't work ? Is there any solution? 
Thank you!

**Comment by marknatera** [comment]
Hey @lwiesel 
Great plugin!
Wanted to know if there is anyway to disable the plugin on mobile?
