### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by anabelLeva** [lwiesel/jquery-fadethis#6]
I would like to use this plugin on my website to load images but it is not working. I have followed all of the necessary steps.

Here is a live version of my site http://anabel.me/testing/portfolio/focus-process-book.html

**Comment by t-geindre** [comment]
Looks like some files are missing.

![js](https://cloud.githubusercontent.com/assets/6348039/7794522/ba9b0be4-02cb-11e5-830f-d1b8ede533f3.png)

**Comment by lwiesel** [comment]
Indeed -as @t-geindre said, it seems that the path to your assets is not correct. You should fix that first.

I'm closing this issue, but don't hesitate to open another one if you encounter any problem with the plugin.
